services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 3s
      retries: 3 
      
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 3s
      retries: 3
        
  worker:
    build:
      context: .
      dockerfile: JobQueue.Worker/Dockerfile 
    environment:
      - ConnectionStrings__Database=Host=db;Database=postgres;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy